### ISSUE TITLE
Minimum IE version CSS-wise

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/iptools-jquery-modal#12]
@davleh based on CSS you produced, what's the minimum IE version we can support CSS-wise?

**Comment by davleh** [comment]
IE 10, IE 9 should degrade nicely

**Comment by ain** [comment]
IE8 is completely out right?

**Comment by davleh** [comment]
For Sennheiser yes

**Comment by ain** [comment]
Ok, thanks.

**Comment by beroes** [comment]
Looks like IE as a whole is out of the game and we shouldn't care of http://www.w3schools.com/browsers/browsers_explorer.asp

**Comment by ain** [comment]
W3Schools is mainly used by devs, the stats are subjective. For any corporate site, the overall picture is very different.
