### ISSUE TITLE
Vendor prefixes needed

### ISSUE THREAD

**Issue by beroes** [interactive-pioneers/iptools-jquery-modal#20]
The lack of vendor specific prefixes when assigning transformations to elements like here https://github.com/interactive-pioneers/iptools-jquery-modal/blob/master/src/iptools-jquery-modal.js#L313  causes bugs on iOS mobile devices: https://redbooth.com/a/index.html#!/projects/1491234/tasks/20835109  
Please add a vendor prefix (at least -webkit) when using CSS3 features.

**Comment by ain** [comment]
Nice catch :+1:

**Comment by ain** [comment]
Fixed with #21.
