### ISSUE TITLE
NPM dependencies out of date

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/iptools-jquery-modal#24]
On build:

```
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
```

**Comment by GeorgMeyer23** [comment]
@ain sub module based dep, we're not able to resolve that one by updating deps.

**Comment by ain** [comment]
Did you manage to scope which ones are problematic and where it comes from?

**Comment by ain** [comment]
Why I'm discussing this is the fact that we've had requests where partners are complaining about errors running through deploy logs. So we have to explain that these are just the warnings from the Bower stack. Not a critical issue, but something that could be improved.

**Comment by ain** [comment]
As @GeorgMeyer23 mentioned, `WARN` messages running through on dependency installation are caused by sub-dependencies and can't be avoided. 

All dependencies have been updated to their latest versions in b6eeda8. Closing.
