### ISSUE TITLE
.modal--vertical-align-center overrides effects like . modal--effect-scale 

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-modal#25]
Alignment and effect classes working with translate3d property, and overides each other.
This is why the effects are not working anymore.

**Comment by GeorgMeyer23** [comment]
transformations may be aligned like: 'transform3d(...) scale3d(...)' and so on...

**Comment by ain** [comment]
Confirmed. Completely gone on SH QA.

**Comment by ain** [comment]
Not a problem of overrides. Tested like this, unfortunately no luck.
