### ISSUE TITLE
Option Z-Index is applied to modal instead of overlay

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-modal#26]

**Comment by davleh** [comment]
@ain @GeorgMeyer23 2 options for discussion:
1. add z-index also to modal
2. remove z-index option completely and set it within css stylesheet as for both overlay and modal window a class can be specified

I would go with the second option. What do you think?

**Comment by GeorgMeyer23** [comment]
I'd go for a default z-index for the overlay in order to work without having to add it via third party class.

**Comment by davleh** [comment]
@GeorgMeyer23 Default css-set z-index or default and overwritable js z-index?

**Comment by ain** [comment]
Please keep in mind that any component should ideally work out of the box functionality-wise, without 3rd party or external CSS, ideally, no CSS at all. It can be super ugly, but it should be robust and solid when it comes to functionality.

**Comment by GeorgMeyer23** [comment]
@davleh 1 - Apply z-index also to modal.
