### ISSUE TITLE
Modal don't close when touch overlay

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-modal#27]
Tested on IPAD2

**Comment by ain** [comment]
Was the option that blocks the overlay click on or off?

**Comment by GeorgMeyer23** [comment]
The same overlay closes on click, option was set correctly.

**Comment by ain** [comment]
I see. Clear bug then.

**Comment by ain** [comment]
Whoever decides to fix this, please incorporate a test. All these bugs are also coming in because such simple use-cases have no written tests.

**Comment by beroes** [comment]
Model is closed by mouseup event attached to the body. Ipad does not have mouse but should have interpret the event as tapup, I think we are talking about iOS bug or something simillar.

**Comment by GeorgMeyer23** [comment]
just implement 'touchstart' event...

**Comment by ain** [comment]
@davleh wasn't this closed with #28?

**Comment by ain** [comment]
Tested against `1.0.4` and `0.2.4`, works. Closing.
