### ISSUE TITLE
Add simple example

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/iptools-jquery-modal#33]
Proposing to add `example/` folder with compiled SCSS, markup and JavaScript that'd render a simple modal out of the box. It could also be used for experimenting and preview.

**Comment by ain** [comment]
@beroes @GeorgMeyer23 @davleh opinions please.

**Comment by GeorgMeyer23** [comment]
:+1:

**Comment by ain** [comment]
Just to note it down: it should also feature:
- Grunt server, like we're usually doing, with LiveReload
- BDD watch task so you get tests (or QA stack) run right on the change
