### ISSUE TITLE
Merge jQuery version branches

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/iptools-jquery-modal#36]
Since component is working across jQuery versions, merge both branches by setting min jQuery version as a dependency.

**Comment by ain** [comment]
@davleh have you had time to make a final confirm if this ticket is safe to go for?

**Comment by GeorgMeyer23** [comment]
:+1:

**Comment by ain** [comment]
@davleh reminding this ticket again, if you have time, please confirm.

**Comment by ain** [comment]
@davleh @GeorgMeyer23 I've just been dealing with some versioning topics on SWD and came to conclusion that we should not define `>=` anywhere, ever. The reason being: it's a break pre-programmed. 

By semver, used by Ruby, Node.js community, major version is always a breaking change and going with `>=` would mean that whenever jQuery Foundation decides to roll out version 3, would be a breaker by concept.

So I think our concept here would need to be `>=1.11.0` and `<3.0.0`.
