### ISSUE TITLE
Add a namespace for the variables defined in scss

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-modal#45]
- avoids conflicts with project internal styling when including the scss file.

**Comment by ain** [comment]
@beroes in case you have time, please feel free to take this one, as per common agreement :)

**Comment by beroes** [comment]
Yep, it make sense.

**Comment by beroes** [comment]
https://github.com/interactive-pioneers/iptools-jquery-modal/commit/3e446ffdad226adc4bd53ecb77c9b5730bfa7d99

**Comment by ain** [comment]
Guys, let's please resort to Pull Requests, always. Makes bugs less likely.

**Comment by GeorgMeyer23** [comment]
@Friedrich-Mocker pls review and tell me what do you think ;)

**Comment by GeorgMeyer23** [comment]
Reviewed, saw added semantic enhancements, all fine, closed!
